# Generated by Django 5.0.3 on 2024-03-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CHOICE', 'Choice'), ('TRUE_FALSE', 'True_False'), ('SHORT_ANSWER', 'Short_Answer')], max_length=50)),
                ('question', models.TextField()),
                ('choices', models.JSONField(blank=True, null=True)),
                ('answer', models.TextField()),
                ('point', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
