# Generated by Django 5.0.6 on 2024-05-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_description_alter_question_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='point',
            field=models.FloatField(),
        ),
    ]
