# Generated by Django 5.0.6 on 2024-05-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_question_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='point',
            field=models.IntegerField(),
        ),
    ]
