# Generated by Django 5.0.3 on 2024-03-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamineeExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('total_time', models.TimeField(blank=True, null=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('flags', models.IntegerField(blank=True, null=True)),
                ('taken', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
