# Generated by Django 5.0.3 on 2024-03-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinee_exams', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examineeexam',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
