# Generated by Django 5.0.2 on 2024-02-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinee_exams', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examineeexam',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='examineeexam',
            name='flags',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examineeexam',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='examineeexam',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examineeexam',
            name='total_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
