# Generated by Django 5.0.6 on 2024-05-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinee_exams', '0004_alter_examineeexam_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examineeexam',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
