# Generated by Django 5.0.2 on 2024-02-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinee_exams', '0004_remove_examineeexam_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examineeexam',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
