# Generated by Django 5.0.3 on 2024-03-14 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_discription_user_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='discription',
            new_name='description',
        ),
    ]
