# Generated by Django 5.0.2 on 2024-02-13 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='exam',
            field=models.ForeignKey(on_delete=models.SET('deleted'), to='exams.exam'),
        ),
        migrations.AddField(
            model_name='payment',
            name='examiner',
            field=models.ForeignKey(on_delete=models.SET('deleted'), to=settings.AUTH_USER_MODEL),
        ),
    ]
