# Generated by Django 5.0.3 on 2024-03-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_payment_max_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='max_questions',
        ),
        migrations.AddField(
            model_name='exam',
            name='max_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
