# Generated by Django 5.0.3 on 2024-03-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_remove_payment_max_questions_exam_max_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='max_questions',
            new_name='max_examinees',
        ),
    ]
