# Generated by Django 5.0.3 on 2024-03-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_exam_total_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='questions_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
