# Generated by Django 5.0.2 on 2024-02-14 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinee_answers', '0002_initial'),
        ('exams', '0003_alter_payment_exam_alter_payment_examiner'),
    ]

    operations = [
        migrations.AddField(
            model_name='examineeanswer',
            name='exam',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exams.exam'),
            preserve_default=False,
        ),
    ]
