# Generated by Django 5.0.3 on 2024-03-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinee_answers', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='type',
            field=models.CharField(choices=[('FACE_LOST', 'Face_Lost'), ('SOMEONE_DETECTED', 'Someone_Detected')], max_length=50),
        ),
    ]
