# Generated by Django 5.0.2 on 2024-02-14 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinee_answers', '0005_alter_examineeanswer_exam'),
        ('exams', '0003_alter_payment_exam_alter_payment_examiner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examineeanswer',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.exam'),
        ),
    ]
