# Generated by Django 5.0.2 on 2024-02-14 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinee_answers', '0010_alter_examineeanswer_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flag',
            name='question',
        ),
        migrations.AddField(
            model_name='flag',
            name='examinee_answer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='examinee_answers.examineeanswer'),
            preserve_default=False,
        ),
    ]
